server_id: 709598806496247828
main_channel: 709598806496247834 # general
welcome_channel: 709598806496247831 # welcome-and-rules
announcement_channel: 709598806496247832 # announcements
readme_channel: 709598806496247831 # welcome-and-rules

bot_id: 735736674025341010
ical_url: "https://calendar.google.com/calendar/ical/uwapcs%40gmail.com/public/basic.ics"

vote_pool_size: 8 # 4 exec + Fresher rep + 3 ocm
vote_role: 709675983204122635 # committee
tiebreaker_role: 735737621183070239 # president
unregistered_member_role: 0 # @unregistered
registered_member_role: 0 # @member
expired_member_role: 0 # @member

command_prefix: "!"

for_vote: "ğŸ‘"
against_vote: "ğŸ‘"
abstain_vote: "ğŸ™Š"
approve_react: "â¬†"
disapprove_react: "â¬‡"
unsure_react: "â”"

react_role_messages:
  - message: 709600566770401381

mention_responses:
  - "Oh hello there"
  - "Stop bothering me. I'm busy."
  - "You know, I'm trying to keep track of this place. I don't need any more distractions."
  - "Don't you have better things to do?"
  - "(sigh) what now?"
  - "Yes, yes, I know I'm brilliant"
  - "What do I need to do to catch a break around here? Eh."
  - "Mmmmhmmm. I'm still around, don't mind me."
  - "You know, some people would consider this rude. Luckily I'm not one of those people. In fact, I'm not even a person."
  - "Perhaps try bothering someone else for a change."

