server_id = 606351521117896704
#general
main_channel = 606351521117896706
#the-corner
welcome_channel = 606351613816209418
#general
announcement_channel = 606351521117896706

bot_id = 607078903969742848

vote_pool_size = 2
vote_role = 607478818038480937
tiebreaker_role = 607509283483025409
unregistered_member_role = 608282247350714408
registered_member_role = 608282133118582815
command_prefix = "!"

for_vote = "ğŸ‘"
against_vote = "ğŸ‘"
abstain_vote = "ğŸ™Š"
approve_react = "â¬†"
disapprove_react = "â¬‡"
unsure_react = "â”"
