server_id: 264401248676085760 # ucc
main_channel: 264401248676085760 # ucc
welcome_channel: 606750983699300372 # welcome
announcement_channel: 264411219627212801 # committee
readme_channel: 674252245008908298 # readme

bot_id: 635407267881156618

vote_pool_size: 8 # 4 exec + Fresher rep + 3 ocm
vote_role: 269817189966544896 # @committee
tiebreaker_role: 0 # No tiebreak apparently 635370432568098817 # @Presiding Presidenterino
unregistered_member_role: 674641042464833548 # @unregistered
registered_member_role: 0 # does not exist

command_prefix: "!"

for_vote: "ğŸ‘"
against_vote: "ğŸ‘"
abstain_vote: "ğŸ™Š"
approve_react: "â¬†"
disapprove_react: "â¬‡"
unsure_react: "â”"

react_role_messages:
  - message: 674652973103579225 # Intro
  - message: 674653014119809025 # Club-related
    mapping:
      uwa: 674254888221278226
      uccl: 674255044006117386
      ğŸ¥¤: 691852097003585577
      cpu: 674255083063738368
      ğŸ®: 691852441091833896
  - message: 674653030817464370 # Operating System
    mapping:
      win10: 674255085307691039
      capple: 674255209916137492
      debian: 674255247824125955
      arch: 674255274957340673
      fedora: 674260517858181122
      linux: 674255299494019093
      bsd: 674255522433859604
  - message: 674653049578455060 # Editor
    mapping:
      vim: 674255633356423208
      emacs: 674255739061010443
      vscode: 674255746833186816
      sublime: 674255747391029249
      atom_: 674255748426891274
      intellij: 674255748959567901
      npp: 674255750297812993
  - message: 674653069526695946 # Programming (1)
    mapping:
      html: 674255751031685130
      css: 674255751707099136
      js: 674255752239775784
      ts: 674255752860532795
      php: 674255753321775134
      python: 674255753787211778
      R_: 674255754278207511
      julia: 674255755305680901
      matlab: 674255755809128448
      mathematica: 674255756320833536
  - message: 674653087075532810 # Programming (2)
    mapping:
      c_: 674256084403224673
      cpp: 674256084826849281
      csharp: 674256086261563442
      java: 674256086748102666
      rust: 674256087180115992
      binary: 674256088199200774
      haskell: 674256088861769738
      ruby: 674256089742835712
      scala: 674256090321387530
      lua: 674256090795474944
      go: 674256091441397761
      tex: 674256092187983897
      git: 674256093064593439
