server_id: 0 #general
main_channel: 0 #the-corner
welcome_channel: 0 #general
announcement_channel: 0 # announcements
readme_channel: 0 # readme

bot_id: 0
ical_url: ""

vote_pool_size: 0
vote_role: 0
tiebreaker_role: 0
unregistered_member_role: 0
registered_member_role: 0
expired_member_role: 0
command_prefix: "!"

for_vote: "ğŸ‘"
against_vote: "ğŸ‘"
abstain_vote: "ğŸ™Š"
approve_react: "â¬†"
disapprove_react: "â¬‡"
unsure_react: "â”"

react_role_messages:
  - message: 0 # message ID
    mapping:
      react: 0 #role number
