server_id = 264401248676085760 # ucc
main_channel = 264401248676085760 # ucc
welcome_channel = 606750983699300372 # welcome
announcement_channel = 264411219627212801 # committee

bot_id = 635407267881156618

vote_pool_size = 7 # 4 exec + 3 ocm
vote_role = 269817189966544896 # @committee
tiebreaker_role = 635370432568098817 # @Presiding Presidenterino
unregistered_member_role = 0 # does not exist
registered_member_role = 0 # does not exist

command_prefix = "!"

for_vote = "ğŸ‘"
against_vote = "ğŸ‘"
abstain_vote = "ğŸ™Š"
approve_react = "â¬†"
disapprove_react = "â¬‡"
unsure_react = "â”"
